# POST - typ požadavku (vytvořit)
# URL - adresa na kterou se požadavek odesílá
# HTTP/1.1 - jde o standarty RFC2616
# Rest klient vyžaduje volný řádek mezi requestem a tělem!
### oddělovač mezi požadavky

POST http://localhost:8080/allMovies
Content-Type: application/json

{
      "image": "http://localhost:3001/movie1.png",
      "title": "Enola Holmesová 2",
      "age": "+13",
      "tags": "Vtipný * Napínavý * Rodina",
      "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
      "price": 100
    }

###
POST http://localhost:8080/allMovies
Content-Type: application/json

{
      "image": "http://localhost:3001/movie2.png",
      "title": "Enola Holmesová",
      "age": "+13",
      "tags": "Vtipný * Napínavý * Rodina",
      "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
      "price": 150
    }

### 
POST http://localhost:8080/allMovies
Content-Type: application/json

  {
      "image": "http://localhost:3001/movie3.png",
      "title": "Rocknrolla",
      "age": "+16",
      "tags": "Gangster * Napínavý * Násilí",
      "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
      "price": 200
    }
    
### 
POST http://localhost:8080/allMovies
Content-Type: application/json

    {
      "image": "http://localhost:3001/movie4.png",
      "title": "Patriot",
      "age": "+16",
      "tags": "Gangster * Napínavý * Násilí",
      "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
      "price": 50
    }

### 
POST http://localhost:8080/allMovies
Content-Type: application/json

    {
      "image": "http://localhost:3001/movie5.png",
      "title": "Telefon pana Harrigana",
      "age": "+16",
      "tags": "Gangster * Napínavý * Násilí",
      "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
      "price": 250
    }

### 
POST http://localhost:8080/allMovies
Content-Type: application/json

    {
      "image": "http://localhost:3001/movie6.png",
      "title": "Stážista",
      "age": "+16",
      "tags": "Rodinný * Napínavý * Romantický",
      "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
      "price": 300
    }

### 
POST http://localhost:8080/allMovies
Content-Type: application/json

    {
      "image": "http://localhost:3001/movie7.png",
      "title": "Život",
      "age": "+13",
      "tags": "Vesmír * Napínavý * Nebezpečí",
      "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
      "price": 175
    }

### 
POST http://localhost:8080/allMovies
Content-Type: application/json

    {
      "image": "http://localhost:3001/movie8.png",
      "title": "Kód za miliardu dolarů",
      "age": "+13",
      "tags": "IT * Napínavý",
      "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
      "price": 225
    }

### 
POST http://localhost:8080/allMovies
Content-Type: application/json

    {
      "image": "http://localhost:3001/movie9.png",
      "title": "Pracháči",
      "age": "+16",
      "tags": "Dokument * Napínavý",
      "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
      "price": 125
    }

### 
POST http://localhost:8080/allMovies
Content-Type: application/json

    {
      "image": "http://localhost:3001/movie10.png",
      "title": "Whoami",
      "age": "+13",
      "tags": "Gangster * Napínavý * Násilí",
      "description": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Autem accusantium amet nemo minus quo architecto quas",
      "price": 375
    }

###
GET http://localhost:8080/allMovies

###
GET http://localhost:8080/allMovies/1

###
PUT http://localhost:8080/allMovies/1
Content-Type: application/json

{
  "id": 1,
  "image": "null",
  "title": "Xový film",
  "age": "5+",
  "tags": "Fun",
  "description": "Daemon",
  "price": 500
}

###
GET http://localhost:8080/allMovies?pageSize=1&pageNumber=1&sortBy=title